services:
  mailhog:
    image: "mailhog/mailhog:latest"
    restart: always
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - production

  user-service:
    build:
      context: ./../user-service
      dockerfile: Dockerfile.dev
    container_name: learnyscape-user-service
    restart: always
    networks:
      - production

  verification-service:
    build:
      context: ./../verification-service
      dockerfile: Dockerfile.dev
    container_name: learnyscape-verification-service
    restart: always
    networks:
      - production

  auth-service:
    build:
      context: ./../auth-service
      dockerfile: Dockerfile.dev
    container_name: learnyscape-auth-service
    restart: always
    networks:
      - production

  admin-service:
    build:
      context: ./../admin-service
      dockerfile: Dockerfile.dev
    container_name: learnyscape-admin-service
    restart: always
    networks:
      - production

  mail-service:
    build:
      context: ./../mail-service
      dockerfile: Dockerfile
    container_name: learnyscape-mail-service
    restart: always
    networks:
      - production

  api-gateway:
    build:
      context: ./../gateway
      dockerfile: Dockerfile.dev
    container_name: learnyscape-api-gateway
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    networks:
      - production

networks:
  production:
    name: production
    external: true