services:
  user-service:
    build:
      context: ./../user-service
      dockerfile: Dockerfile.dev
    container_name: learnyscape-user-service
    restart: always
    ports: # temporary for local testing
      - "8081:8000"
    networks:
      - production

  auth-service:
    build:
      context: ./../auth-service
      dockerfile: Dockerfile.dev
    container_name: learnyscape-auth-service
    restart: always
    networks:
      - production

  api-gateway:
    build:
      context: ./../gateway
      dockerfile: Dockerfile.dev
    container_name: learnyscape-api-gateway
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    networks:
      - production

networks:
  production:
    name: production
    external: true