services:
  pg-user-1: &pg-user-common
    image: "bitnami/postgresql-permgr:latest"
    restart: always
    container_name: pg-user-1
    env_file:
      - .env.pgpool
    environment: &pg-user-env
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRESQL_POSTGRES_PASSWORD_USER}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD_USER}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE_USER}
      REPMGR_PRIMARY_HOST: pg-user-1
      REPMGR_PARTNER_NODES: pg-user-1,pg-user-2,pg-user-3
      REPMGR_NODE_NAME: pg-user-1
      REPMGR_NODE_NETWORK_NAME: pg-user-1
      REPMGR_USERNAME: repmgr
      REPMGR_PASSWORD: repmgr
    volumes:
      - pg_user_1_data:/bitnami/postgresql

  pg-user-2:
    <<: *pg-user-common
    container_name: pg-user-2
    environment:
      <<: *pg-user-env
      REPMGR_PARTNER_NODES: pg-user-1,pg-user-2,pg-user-3
      REPMGR_NODE_NAME: pg-user-2
      REPMGR_NODE_NETWORK_NAME: pg-user-2
    volumes:
      - pg_user_2_data:/bitnami/postgresql

  pg-user-3:
    <<: *pg-user-common
    container_name: pg-user-3
    environment:
      <<: *pg-user-env
      REPMGR_PARTNER_NODES: pg-user-1,pg-user-2,pg-user-3
      REPMGR_NODE_NAME: pg-user-3
      REPMGR_NODE_NETWORK_NAME: pg-user-3
    volumes:
      - pg_user_3_data:/bitnami/postgresql

  pgpool-user:
    image: "bitnami/pgpool:latest"
    restart: always
    container_name: pgpool-user
    env_file:
      - .env.pgpool
    environment:
      PGPOOL_BACKEND_NODES: 0:pg-user-1:5432,1:pg-user-2:5432,2:pg-user-3:5432
      PGPOOL_SR_CHECK_USER: repmgr
      PGPOOL_SR_CHECK_PASSWORD: repmgr
      PGPOOL_POSTGRES_USERNAME: ${PGPOOL_POSTGRES_USERNAME_USER}
      PGPOOL_POSTGRES_PASSWORD: ${PGPOOL_POSTGRES_PASSWORD_USER}
      PGPOOL_ADMIN_USERNAME: ${PGPOOL_ADMIN_USERNAME_USER}
      PGPOOL_ADMIN_PASSWORD: ${PGPOOL_ADMIN_PASSWORD_USER}
      PGPOOL_ENABLE_LOAD_BALANCING: yes
    ports:
      - "5000:5432"
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_user_1_data:
  pg_user_2_data:
  pg_user_3_data:

networks:
  default:
    name: production
    external: true