services:
  auth-service:
    build:
      context: ./../auth-service
      dockerfile: Dockerfile.dev
    container_name: learnyscape-auth-service
    restart: always
    networks:
      - development

  api-gateway:
    build:
      context: ./../gateway
      dockerfile: Dockerfile.dev
    container_name: learnyscape-api-gateway
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    networks:
      - development

networks:
  development:
    name: development
    external: true